/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorInicioSesion;
import modelos.Usuario;

/**
 *
 * @author kevin
 */
public class FormInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form FormIniciosesion
     */
    public FormInicioSesion() {
        initComponents();
    }
    
    public Usuario obtenerUsuario(){
        String usuario = this.campoUsuario.getText();
        String clave = new String(this.campoClave.getPassword());
        return new Usuario(usuario,clave);
    }
    
    public void agregarEventos(ControladorInicioSesion controlador){
        this.botonIniciarSesion.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelCampos = new javax.swing.JPanel();
        etiquetaUsuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        etiquetaClave = new javax.swing.JLabel();
        campoClave = new javax.swing.JPasswordField();
        panelBoton = new javax.swing.JPanel();
        botonIniciarSesion = new javax.swing.JButton();
        panelTitulo = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        setPreferredSize(new java.awt.Dimension(350, 350));
        setResizable(false);

        panelCampos.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 50, 50, 50));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {0.1, 0.4, 0.25, 0.25};
        panelCampos.setLayout(jPanel1Layout);

        etiquetaUsuario.setText("Nombre de usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCampos.add(etiquetaUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelCampos.add(campoUsuario, gridBagConstraints);

        etiquetaClave.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelCampos.add(etiquetaClave, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelCampos.add(campoClave, gridBagConstraints);

        getContentPane().add(panelCampos, java.awt.BorderLayout.CENTER);

        botonIniciarSesion.setText("Iniciar sesión");
        botonIniciarSesion.setName("iniciar_sesion"); // NOI18N
        panelBoton.add(botonIniciarSesion);

        getContentPane().add(panelBoton, java.awt.BorderLayout.SOUTH);

        panelTitulo.setBackground(new java.awt.Color(0, 102, 255));

        etiquetaTitulo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setText("Entrada a MiConsultorio");
        panelTitulo.add(etiquetaTitulo);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
