/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorRegistroMedicamento;
import modelos.Medicamento;

/**
 *
 * @author amoel
 */
public class FormMedicamento extends javax.swing.JFrame {

    private boolean actualizar;
    private Medicamento medicamento;
    /**
     * Creates new form RegistroMedicamento
     */
    public FormMedicamento() {
        initComponents();
    }
    
    public void cargarMedicamento(Medicamento medicamento){
        this.medicamento = medicamento;
        txtNombre.setText(medicamento.getNombre());
        spinnerExistencia.setValue(medicamento.getExistencia());
    }
    
    public Medicamento obtenerMedicamento(){
        medicamento.setNombre(obtenerContenidoNombre());
        medicamento.setExistencia(obtenerContenidoExistencia());
        return medicamento;
    }

    public boolean getActualizar() {
        return actualizar;
    }

    public void setActualizar(boolean actualizar) {
        this.actualizar = actualizar;
    }
    
    // Método para obtener el contenido de txtExistencia
    public int obtenerContenidoExistencia() {
        return (int)spinnerExistencia.getValue();
    }

    // Método para limpiar el contenido de txtExistencia
    public void limpiarExistencia() {
        spinnerExistencia.setValue(1);
    }


    // Método para obtener el contenido de txtNombre
    public String obtenerContenidoNombre() {
        return txtNombre.getText();
    }

    // Método para limpiar el contenido de txtNombre
    public void limpiarNombre() {
        txtNombre.setText("");
    }
    
    
    public boolean tieneCamposVacios(){
        return txtNombre.getText().isEmpty() || (int)spinnerExistencia.getValue() == 0;
    }
    
    public void limpiar(){
        limpiarExistencia();
        limpiarNombre();
    }
    
    
    public void agregarEventos(ControladorRegistroMedicamento controlador){
        this.botonGuardar.addActionListener(controlador);
        this.botonCancelar.addActionListener(controlador);
        this.spinnerExistencia.addChangeListener(controlador);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        etiquetaExistencia = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spinnerExistencia = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo medicamento");
        setResizable(false);

        etiquetaTitulo.setBackground(new java.awt.Color(51, 102, 255));
        etiquetaTitulo.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Registro de Medicamento");
        etiquetaTitulo.setOpaque(true);

        botonGuardar.setText("Guardar");
        botonGuardar.setName("guardar"); // NOI18N

        botonCancelar.setText("Cancelar");
        botonCancelar.setName("cancelar"); // NOI18N

        etiquetaExistencia.setText("Existencia:");

        etiquetaNombre.setText("Nombre:");

        spinnerExistencia.setValue(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaExistencia)
                            .addComponent(etiquetaNombre))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(spinnerExistencia)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelar)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaExistencia)
                    .addComponent(spinnerExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonGuardar;
    private javax.swing.JLabel etiquetaExistencia;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JSpinner spinnerExistencia;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables


}
